name: Binary build
on:
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: build
        run: pyinstaller --onefile src/chemical_viewer/__main__.py -n chemical-viewer --collect-all chemical-viewer

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: chemical-viewer-windows
          path: dist/windows/chemical-viewer.exe

  macOS-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: build
        run: pyinstaller --onefile src/chemical_viewer/__main__.py -n chemical-viewer --collect-all chemical-viewer

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: chemical-viewer-macos
          path: dist/macos/chemical-viewer

  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: build
        run: pyinstaller --onefile src/chemical_viewer/__main__.py -n chemical-viewer --collect-all chemical-viewer

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: chemical-viewer-linux
          path: dist/linux/chemical-viewer

  release:
    needs: [ubuntu-build, macOS-build, windows-build]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux
        uses: actions/download-artifact@v4
        with:
          name: chemical-viewer-linux

      - name: Download Mac
        uses: actions/download-artifact@v4
        with:
          name: chemical-viewer-macos

      - name: Download Windows
        uses: actions/download-artifact@v4
        with:
          name: chemical-viewer-windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip
        run: |
          tar -C chemical-viewer-macos -pczvf chemical-viewer-macos.tar.gz chemical-viewer
          tar -C chemical-viewer-linux -pczvf chemical-viewer-linux.tar.gz chemical-viewer
          zip --junk-paths chemical-viewer-windows ./chemical-viewer-windows/chemical-viewer.exe
      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chemical-viewer-macos.tar.gz
          asset_name: chemical-viewer-macos.tar.gz
          asset_content_type: application/gzip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chemical-viewer-linux.tar.gz
          asset_name: chemical-viewer-linux.tar.gz
          asset_content_type: application/gzip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chemical-viewer-windows.zip
          asset_name: chemical-viewer-windows.zip
          asset_content_type: application/zip
